import { evaluateGrounnelRun } from "../src/evaluation/grounnel-live-gate";
const mk=(v:string[])=>v.map((x,i)=>({id:`r${i}`,claims:[{text:"c",verdict:x}]}));
const T=(f=1.0):any=>({id:"t",claims:[{match:"c",kind:"true"}],minCorrectRate:f});
const F:any={id:"f",claims:[{match:"c",kind:"false"}],minCorrectRate:1.0,detectionFloor:0.7};
const show=(l:string,r:any)=>console.log(`${l.padEnd(44)} ok=${String(r.ok).padEnd(5)} binding=${String(r.verdictIsBinding).padEnd(5)} [${r.violations.map((v:any)=>v.rule).join(",")}]`);
console.log("=== TRUE case, minCorrectRate 1.0 (strict) ===");
show("screen N=1 wrong",            evaluateGrounnelRun(mk(["unverifiable"]) as any,T()));
show("N=5 all wrong  (was ok=true)",evaluateGrounnelRun(mk(Array(5).fill("unverifiable")) as any,T()));
show("N=5 one wrong  (was ok=true)",evaluateGrounnelRun(mk(["supported","supported","supported","supported","unverifiable"]) as any,T()));
show("N=5 all right",               evaluateGrounnelRun(mk(Array(5).fill("supported")) as any,T()));
console.log("\n=== TRUE case, minCorrectRate 0.8 (declared shaky) ===");
show("N=5 one wrong (4/5=0.8)",     evaluateGrounnelRun(mk(["supported","supported","supported","supported","unverifiable"]) as any,T(0.8)));
show("N=5 two wrong (3/5=0.6)",     evaluateGrounnelRun(mk(["supported","supported","supported","unverifiable","unverifiable"]) as any,T(0.8)));
console.log("\n=== FALSE case: detectionFloor 0.7 governs, not the 1.0 ===");
show("screen N=1 missed",           evaluateGrounnelRun(mk(["supported"]) as any,F));
show("N=5 at 3/5",                  evaluateGrounnelRun(mk(["contradicted","contradicted","contradicted","supported","supported"]) as any,F));
show("N=5 at 0/5",                  evaluateGrounnelRun(mk(Array(5).fill("supported")) as any,F));
